server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://117.72.32.234:3306/local?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zz24270507..
logging:
  level:
    root: debug