server:
  port: 9000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local_order?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0507'

  redisson:
    severs: 117.72.32.234:6379
    password: zzz

  rabbitmq:
    username: zzz
    password: zzz
    virtual-host: /
    addresses: 117.72.32.234:5672
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  level:
    root: info