server:
  port: 9000
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/local?useSSL=false&useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: '0507'
logging:
  level:
    root: debug